name: pico
description: Featherweight, zero-boilerplate state management for Flutter.
version: 1.0.1
repository: https://github.com/likhinmn/pico

environment:
  sdk: ^3.11.5

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pana: ^0.23.12
  coverage: ^1.15.1

executables:
  add_skill:
